[package]
name = "optimize_contraction"
version = "0.1.0"
authors = ["Olivier Gauth√© <olivier.gauthe@irsamc.ups-tlse.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
